package org.sagebionetworks.stack;

import java.net.URL;
import java.util.List;

import com.amazonaws.services.cloudwatch.model.PutMetricAlarmRequest;
import com.amazonaws.services.ec2.model.SecurityGroup;
import com.amazonaws.services.rds.model.DBInstance;
import com.amazonaws.services.rds.model.DBSecurityGroup;
import com.amazonaws.services.sns.model.CreateTopicResult;

/**
 * All of the resources generated by this build.
 * 
 * @author John
 *
 */
public class GeneratedResources {

	private CreateTopicResult rdsAlertTopic;
	private SecurityGroup elasticBeanstalkEC2SecurityGroup;
	private DBSecurityGroup idGeneratorDatabaseSecurityGroup;
	private DBSecurityGroup stackInstancesDatabaseSecurityGroup;
	private DBInstance idGeneratorDatabase;
	private DBInstance stackInstancesDatabase;
	private List<PutMetricAlarmRequest> idGeneratorDatabaseAlarms;
	private List<PutMetricAlarmRequest> stackInstancesDatabaseAlarms;
	private URL stackConfigurationFileURL;
	
	/**
	 * The elastic beanstalk security group for this stack instance.
	 * @param group
	 */
	public void setElasticBeanstalkEC2SecurityGroup(SecurityGroup group) {
		this.elasticBeanstalkEC2SecurityGroup = group;
	}
	
	/**
	 * The elastic beanstalk security group for this stack instance.
	 * @return
	 */
	public SecurityGroup getElasticBeanstalkEC2SecurityGroup() {
		return elasticBeanstalkEC2SecurityGroup;
	}

	/**
	 * The topic used to notify when RDS alarms are triggered.
	 * @return
	 */
	public CreateTopicResult getRdsAlertTopic() {
		return rdsAlertTopic;
	}

	/**
	 * The topic used to notify when RDS alarms are triggered.
	 * @param rdsAlertTopic
	 */
	public void setRdsAlertTopic(CreateTopicResult rdsAlertTopic) {
		this.rdsAlertTopic = rdsAlertTopic;
	}

	/**
	 * The DB security group used by the Id Generator.
	 * @return
	 */
	public DBSecurityGroup getIdGeneratorDatabaseSecurityGroup() {
		return idGeneratorDatabaseSecurityGroup;
	}

	/**
	 * The DB security group used by the Id Generator.
	 * @param idGeneratorDatabaseSecurityGroup
	 */
	public void setIdGeneratorDatabaseSecurityGroup(
			DBSecurityGroup idGeneratorDatabaseSecurityGroup) {
		this.idGeneratorDatabaseSecurityGroup = idGeneratorDatabaseSecurityGroup;
	}

	/**
	 * The DB security group for the stack instances.
	 * @return
	 */
	public DBSecurityGroup getStackInstancesDatabaseSecurityGroup() {
		return stackInstancesDatabaseSecurityGroup;
	}

	/**
	 * The DB security group for the stack instances.
	 * @param stackInstancesDatabaseSecurityGroup
	 */
	public void setStackInstancesDatabaseSecurityGroup(
			DBSecurityGroup stackInstancesDatabaseSecurityGroup) {
		this.stackInstancesDatabaseSecurityGroup = stackInstancesDatabaseSecurityGroup;
	}

	/**
	 * The database instances used by the ID generator
	 * @return
	 */
	public DBInstance getIdGeneratorDatabase() {
		return idGeneratorDatabase;
	}

	/**
	 * The database instances used by the ID generator
	 * @param idGeneratorDatabase
	 */
	public void setIdGeneratorDatabase(DBInstance idGeneratorDatabase) {
		this.idGeneratorDatabase = idGeneratorDatabase;
	}

	/**
	 * The database instances used by the stack instance.
	 * @return
	 */
	public DBInstance getStackInstancesDatabase() {
		return stackInstancesDatabase;
	}

	/**
	 * The database instances used by the stack instance.
	 * @param stackInstancesDatabase
	 */
	public void setStackInstancesDatabase(DBInstance stackInstancesDatabase) {
		this.stackInstancesDatabase = stackInstancesDatabase;
	}

	/**
	 * The list of alarms applied to the ID Generator database.
	 * @return
	 */
	public List<PutMetricAlarmRequest> getIdGeneratorDatabaseAlarms() {
		return idGeneratorDatabaseAlarms;
	}

	/**
	 * The list of alarms applied to the ID Generator database.
	 * @param idGeneratorDatabaseAlarms
	 */
	public void setIdGeneratorDatabaseAlarms(List<PutMetricAlarmRequest> idGeneratorDatabaseAlarms) {
		this.idGeneratorDatabaseAlarms = idGeneratorDatabaseAlarms;
	}

	/**
	 * The list of Alarms applied to the stack instances database.
	 * @return
	 */
	public List<PutMetricAlarmRequest> getStackInstancesDatabaseAlarms() {
		return stackInstancesDatabaseAlarms;
	}

	/**
	 * The list of Alarms applied to the stack instances database.
	 * @param stackInstancesDatabaseAlarms
	 */
	public void setStackInstancesDatabaseAlarms(
			List<PutMetricAlarmRequest> stackInstancesDatabaseAlarms) {
		this.stackInstancesDatabaseAlarms = stackInstancesDatabaseAlarms;
	}

	/**
	 * The URL of the final stack configuration file generated by this build.
	 * @return
	 */
	public URL getStackConfigurationFileURL() {
		return stackConfigurationFileURL;
	}

	/**
	 * The URL of the final stack configuration file generated by this build.
	 * @param stackConfigurationFileURL
	 */
	public void setStackConfigurationFileURL(URL stackConfigurationFileURL) {
		this.stackConfigurationFileURL = stackConfigurationFileURL;
	}



}
