name: Build and run unit tests

on:
  pull_request:
    branches: [develop, release-*]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - run: mvn --batch-mode clean test
